stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project"

test_job:
  stage: test
  script:
    - echo "Running tests"

deploy_pages:
  stage: deploy
  script:
    - echo "Deploying GitLab Pages"
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Publishing GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - master