stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project"
  artifacts:
    paths:
      - my_artifact.txt

test_job:
  stage: test
  script:
    - echo "Running tests"

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project"